config/routes.rb
Rails.application.routes.draw do
	resources :planets, only: [:index, :show, :new, :create]
	resources :alien_races, only: [:index, :show, :new, :create]
	resources :populations, only: [:new, :create, :show]
end

app/models/alien_race.rb
class AlienRace < ApplicationRecord
	has_many :populations
	has_many :planets, through: :populations

	validates :name, presence: true, uniqueness: true
	validates :biome, presence: true
	validates :demeanor, presence: true
	validates :description, presence: true

	validate :genus_species

	def genus_species
		if name.split.length != 2
			errors.add(:name, "Must be written in the 'genus species' format")
		end
	end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/planet.rb
class Planet < ApplicationRecord
	has_many :populations
	has_many :alien_races, through: :populations

	validates :name, presence: true, uniqueness: true
	validates :climate, presence: true
	validates :size, presence: true
	validates :size, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 5}
	validates :description, presence: true
end

app/models/population.rb
class Population < ApplicationRecord
	belongs_to :planet
	belongs_to :alien_race

	validates :size, presence: true
	validates :size, numericality: {greater_than: 0}
	validates :alien_race, uniqueness: {scope: :planet}
	# validate :unique_relation

	# def unique_relation
	# 	if Population.find_by(alien_race_id: alien_race_id, planet_id: planet_id)
	# 		errors.add(:population, "of #{AlienRace.find(alien_race_id).name} already exists on #{Planet.find(planet_id).name}")
	# 	end

	# end



	def size_input=(input)
		if input.to_i == 0
			self.extinct = true
		else
			self.extinct = false
		end

		self.size = input
	end
end

app/controllers/alien_races_controller.rb
class AlienRacesController < ApplicationController
	def new
		@alien_race = AlienRace.new
	end

	def create
		@alien_race = AlienRace.new(alien_race_params)
		if @alien_race.save
			redirect_to alien_race_path(@alien_race)
		else
			render :new
		end
	end

	def index
		@alien_races = AlienRace.all
	end

	def show
		@alien_race = AlienRace.find(params[:id])
	end

	private

	def alien_race_params
		params.require(:alien_race).permit(:name, :biome, :demeanor, :description)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :errors

	def errors(object)
		object.errors.full_messages
	end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
	def new
		@planet = Planet.new
	end

	def create
		@planet = Planet.new(planet_params)
		if @planet.save
			redirect_to planet_path(@planet)
		else
			render :new
		end
	end

	def index
		@planets = Planet.all
	end

	def show
		@planet = Planet.find(params[:id])
	end

	private

	def planet_params
		params.require(:planet).permit(:name, :climate, :size, :description)
	end
end

app/controllers/populations_controller.rb
class PopulationsController < ApplicationController

	def create
		@population = Population.new(population_params)

		if @population.save
			if params[:population][:page] == "planet page"
				redirect_to planet_path(Planet.find(params[:population][:planet_id]))
			elsif params[:population][:page] == "alien race page"
				redirect_to alien_race_path(AlienRace.find(params[:population][:alien_race_id]))
			else
				redirect_to population_path(@population)
			end
		else 
			render :new
		end

	end

	def new
		@population = Population.new
	end

	def show
		@population = Population.find(params[:id])
	end


	private

	def population_params
		params.require(:population).permit(:planet_id, :alien_race_id, :size_input)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alien_races/index.html.erb
<h1>Alien Races</h1>

<%= link_to "Enter a new alien race", new_alien_race_path %>


<ul>

	<% @alien_races.each do |alien_race| %>

	<li><%= link_to alien_race.name, alien_race_path(alien_race) %></li>

	<% end %>
</ul>

app/views/alien_races/new.html.erb
<h1>New Alien Race</h1>
<ul>
	<% errors(@alien_race).each do |error| %>
		<li><%= error %></li>
	<% end %>
</ul>

<%= form_for @alien_race do |f|%>

	<%= f.label :name %>
	<%= f.text_field :name %>

	<br>

	<%= f.label :biome %>
	<%= f.text_field :biome %>

	<br>

	<%= f.label :demeanor %>
	<%= f.text_field :demeanor %>

	<br>

	<%= f.label :description %>
	<%= f.text_area :description %>

	<br>

	<%= f.submit "Create Alien Race" %>

<% end %>

app/views/alien_races/show.html.erb
<h1><%= @alien_race.name %></h1>

<p>Biome: <%= @alien_race.biome %></p>
<p>Demeanor: <%= @alien_race.demeanor %></p>
<p>Description: <%= @alien_race.description %></p>


<br>
<br>
<br>


<h3>Planets</h3>
<table>
<% @alien_race.populations.each do |population| %>
	<tr>
		<td>Planet: <%= link_to population.planet.name, planet_path(population.planet) %></td>
		<td>Population size: <%= population.size %></td>
		<td>Extinct: <%= population.extinct %></td>
	</tr>
<% end %>
</table>

<h4>Add a new populace</h4>
<%= form_for :population, url: populations_path do |f| %>
	<%= f.collection_select :planet_id, Planet.all, :id, :name %>
	<%= f.label :size, for: :population_size_input %>
	<%= f.number_field :size_input%>
	<%= f.hidden_field :alien_race_id, value: @alien_race.id %>
	<%= f.hidden_field :page, value: "alien race page" %>
	<%= f.submit "Add populace" %>
<% end %>

<br>
<br>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HHGG</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<menu>
  		<%= link_to "Alien Races", alien_races_path%>
  		<%= link_to "Planets", planets_path %>
  	</menu>
    <%= yield %>
  </body>
</html>

app/views/planets/index.html.erb
<h1>Planets</h1>

<%= link_to "Enter a new planet", new_planet_path %>

<ul>

	<% @planets.each do |planet| %>

	<li><%= link_to planet.name, planet_path(planet) %></li>

	<% end %>
</ul>

app/views/planets/new.html.erb
<h1>New Planet</h1>

<ul>
	<% errors(@planet).each do |error| %>
		<li><%= error %></li>
	<% end %>
</ul>


<%= form_for @planet do |f|%>

	<%= f.label :name %>
	<%= f.text_field :name %>

	<br>

	<%= f.label :climate %>
	<%= f.text_field :climate %>

	<br>

	<%= f.label :size %> <text>(1-5)</text>
	<%= f.number_field :size %>

	<br>

	<%= f.label :description %>
	<%= f.text_area :description %>

	<br>

	<%= f.submit "Create Planet" %>

<% end %>

app/views/planets/show.html.erb
<h1><%= @planet.name %></h1>

<p>Climate: <%= @planet.climate %></p>
<p>Size: <%= @planet.size %></p>
<p>Description: <%= @planet.description %></p>


<br>
<br>
<br>

<h3>Alien Races</h3>
<table>
<% @planet.populations.each do |population| %>
	<tr>
		<td>Alien Race: <%= link_to population.alien_race.name, alien_race_path(population.alien_race) %></td>
		<td>Population size: <%= population.size %></td>
		<td>Extinct: <%= population.extinct %></td>
	</tr>
<% end %>
</table>


<h4>Add a new populace</h4>
<%= form_for :population, url: populations_path do |f| %>
	<%= f.collection_select :alien_race_id, AlienRace.all, :id, :name %>
	<%= f.label :size, for: :population_size_input %>
	<%= f.number_field :size_input%>
	<%= f.hidden_field :planet_id, value: @planet.id %>
	<%= f.hidden_field :page, value: "planet page" %>
	<%= f.submit "Add populace" %>
<% end %>

<br>
<br>
<br>

app/views/populations/new.html.erb
<h1>New Population</h1>
<ul>
<% errors(@population).each do |error| %>
	<li><%= error %></li>
<% end %>
</ul>

<%= form_for @population do |f| %>
	<%= f.label :size, for: :population_size_input %>
	<%= f.number_field :size_input, value: :size %>

	<br>
	
	<%= f.collection_select :alien_race_id, AlienRace.all, :id, :name %>
	<br>
	<%= f.collection_select :planet_id, Planet.all, :id, :name %>
	<br>
	
	<%= f.submit "Create Population" %>

<% end %>

app/views/populations/show.html.erb
<h1>Population of <%= @population.alien_race.name %> living on <%= @population.planet.name %></h1>
<p>Population size: <%= @population.size %></p>
<p>Extinct: <%= @population.extinct %></p>